site_name: Documentation Demo
site_description: Docs-as-code demonstration
# site_url: https://sorbieskis.github.io/docs-as-code-demo/  # Commented for local development

repo_url: https://github.com/Sorbieskis/docs-as-code-demo
repo_name: sorbieskis/docs-as-code-demo

theme:
  name: material
  features:
    - navigation.top
    - search.highlight

plugins:
  - search
  - with-pdf:
      author: Demo Project
      copyright: "2024"
      cover_title: Documentation Demo
      output_path: pdf/manual.pdf
      cover_subtitle: Automated Documentation Pipeline
      custom_template_path: template.latex

nav:
  - Home: index.md

markdown_extensions:
  - toc
  - tables
  - fenced_code