site_name: Project Unidoc
site_description: Enterprise Documentation Management System - Scalable multi-manual
  platform with automated workflows
repo_url: https://github.com/Sorbieskis/docs-as-code-demo
repo_name: sorbieskis/docs-as-code-demo
theme:
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: light blue
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.highlight
  - toc.integrate
  - content.code.copy
nav:
- Home: index.md
- Manuals:
  - CRS10 Software Manual: crs10-software-manual.md
  - System Architecture Guide: system-architecture.md
  - Project Unidoc Overview: unidoc-overview.md
plugins:
- search
- git-revision-date-localized:
    type: date
    locale: en
- with-pdf:
    author: Project Unidoc Team
    copyright: 2024 Enterprise Documentation Solutions
    cover_title: Project Unidoc
    output_path: pdf/unidoc-manual.pdf
    cover_subtitle: Enterprise Documentation Management System
    custom_template_path: template.latex
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
- tables
- fenced_code
