[build]
  # Build command that assembles manuals and builds the MkDocs site
  command = "python assemble.py && mkdocs build"
  
  # Directory that contains the built site
  publish = "site/"

[build.environment]
  # Python version for MkDocs and dependencies
  PYTHON_VERSION = "3.11"

# Plugin removed - not needed for this project

# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect configuration for admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Netlify Identity will be enabled via the Netlify dashboard