backend:
  name: github
  repo: Sorbieskis/docs-as-code-demo
  branch: main

# For local testing only
# backend:
#   name: test-repo

# Alternative: Git Gateway for local development
# backend:
#   name: git-gateway
#   branch: main

# Local development with decap-server (port 8081)
local_backend: true

# Media files
media_folder: "docs/assets/images"
public_folder: "/assets/images"

# Publish mode
publish_mode: editorial_workflow

# Collections
collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Sorbieskis"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "config"
    label: "Site Configuration"
    files:
      - label: "Navigation & Site Settings"
        name: "mkdocs_config"
        file: "mkdocs.yml"
        fields:
          - {label: "Site Name", name: "site_name", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Site URL", name: "site_url", widget: "string"}
          - {label: "Repository URL", name: "repo_url", widget: "string"}
          - label: "Navigation"
            name: "nav"
            widget: "list"
            fields:
              - {label: "Page Title", name: "title", widget: "string"}
              - {label: "File Path", name: "path", widget: "string"}

# Editor settings
editor:
  preview: true

# Site URL for preview
site_url: https://sorbieskis.github.io/docs-as-code-demo

# Display URL
display_url: https://sorbieskis.github.io/docs-as-code-demo

# Logo
logo_url: https://decapcms.org/img/decap-logo.svg