backend:
  name: github
  repo: Sorbieskis/docs-as-code-demo
  branch: main

local_backend: true

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "markdown"}

editor:
  preview: true