backend:
  name: git-gateway
  branch: main

media_folder: 'docs/assets/images'
public_folder: '/assets/images'

collections:
  # Content Components Collection - Simplified for Phase 2
  - name: 'components'
    label: 'Content Components'
    label_singular: 'Component'
    description: 'Edit content components that will be used to build manuals'
    folder: 'docs/content/components'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Component Type'
        name: 'component_type'
        widget: 'select'
        options: ['reusable', 'unique']
        default: 'unique'
      - label: 'Content'
        name: 'body'
        widget: 'markdown'

editor:
  preview: true