backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Content", name: "body", widget: "markdown"}

editor:
  preview: true